### ISSUE TITLE
Control buttons in video

### ISSUE THREAD

**Issue by anastasia77705** [UNICEFECAR/parent-buddy-mobile#104]
Home screen/Articles | When watching video in full screen, control buttons (play/pause, settings) of a media player are cut off on the bottom | Go to article with video, play video | https://drive.google.com/file/d/1AzQMl6Sd2fqGiJbZOUqNVY4TnciK5SGc/view?usp=sharing | Matea | matea.zilak@fer.hr | Samsung Galaxy S20 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by mi5ha** [comment]
Solved with [this](https://github.com/byteout/halo-beba/commit/49ae3fd289c6cd2f88c66f82259294314bedc244) commit
