### ISSUE TITLE
Do not allow user to enter measurements for future periods

### ISSUE THREAD

**Issue by anastasia77705** [UNICEFECAR/parent-buddy-mobile#105]
Child Growth/ New measurement | A user is allowed to fill a new measurement on the future date | Fill the screen with new measurement with data and pick date after today | https://drive.google.com/file/d/1yH4UorYbnfksRoTHVdipCnN3eQuNlOVv/view?usp=sharing | Matea | matea.zilak@fer.hr | Samsung Galaxy S20 | New feature |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by MilosByteOut** [comment]
closed: https://github.com/byteout/halo-beba/commit/659da5caa765428269ba59f2fc9140059f868f9a
