### ISSUE TITLE
Message "Data Export is Successful"

### ISSUE THREAD

**Issue by anastasia77705** [UNICEFECAR/parent-buddy-mobile#113]
Settings | Export data doesn't have any feedback | Click on Export button shows loading circle but after it is finished there is no message for successful export. When I go to my Google drive, the ParrentBuddy folder is created with my.backup file. It would be useful to have a notification after the export is done where a user can find the data on his drive |   | Matea | matea.zilak@fer.hr | Samsung Galaxy S20 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by MilosByteOut** [comment]
closed 97300595212d161a0aa2ee1cdfb69c001da3aa5c
