### ISSUE TITLE
Video player on Android

### ISSUE THREAD

**Issue by anastasia77705** [UNICEFECAR/parent-buddy-mobile#114]
Home screen/Articles | At the end of a video, a screen for embeeding the video is shown | Go to article with video, play the video till the end. Is it possible to not to show this screen but instead of this show screen for playing again the video or simply returning to the article? | https://drive.google.com/file/d/1QOQDMU4Ztq62CXAjFlzg-LEzLGVpvjJF/view?usp=sharing | Matea | matea.zilak@fer.hr | Samsung Galaxy S20 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by mi5ha** [comment]
Solved with [this](https://github.com/byteout/halo-beba/commit/49ae3fd289c6cd2f88c66f82259294314bedc244) commit
