### ISSUE TITLE
Possible to add sister or brother without name and picture (Android)

### ISSUE THREAD

**Issue by anastasia77705** [UNICEFECAR/parent-buddy-mobile#119]
Introduce your child | Possible to add sister or brother without name and picture | After already having introduced one child in the app, go to setting to add a sister or a brother and without adding any information click on Save. You will get a warning to add all names but the profile will be shown under the first child and it can be activated | https://drive.google.com/file/d/1dZucX6lV1ERTffJ4txO1sEWLBzIlt6Ri/view?usp=sharing | Matea | matea.zilak@fer.hr | Samsung Galaxy S20 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

Anastasia could not reproduce this bug on IPhone.

**Comment by MilosByteOut** [comment]
bea1b929c368a95f510d4261b0c85b367b471c68 closed
