### ISSUE TITLE
Translate button in Terms and condition in English

### ISSUE THREAD

**Issue by anastasia77705** [UNICEFECAR/parent-buddy-mobile#124]
Terms and Conditions/Uslovi koriscenja aplikacije | Terms and conditions text shows 2 times. When using English, the button for accepting the terms is shown with Serbian text | See screenshot from the link on the rigth | https://drive.google.com/file/d/1_Cop_vEAyOQcLk9_PJryOtDEy61YLWDn/view?usp=sharing | Matea | matea.zilak@fer.hr | Samsung Galaxy S20 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

Anastasia's comment:
- Translate it the button to "Accept terms and conditions"
- I will erase Terms and conditions text with is shown 2 times from CMS

**Comment by MilosByteOut** [comment]
closed 72a87fec55d9b6ffcdec8184e32078dfd3ae7313
