### ISSUE TITLE
Do not show Vanredni pregled card if child is measured At home in Growth Functionality

### ISSUE THREAD

**Issue by anastasia77705** [UNICEFECAR/parent-buddy-mobile#136]
Health check-ups | Kada se unese da je dete mereno kod kuce on opet upisuje kao vandredni pregled kod doktora. Ok je ako se upisuje pregled kada se pobelezi da je dete mereno kod lekara. | Ovaj skrin 16.09. je uneseno kao mereno kod kuce a 23.09. kod doktora | https://drive.google.com/file/d/19IO57Dj4BVJOkfH36h3tiaC_DaYImnRi/view?usp=sharing | Jelena | jzajeganovic@unicef.org | Samsung A51 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by mi5ha** [comment]
- [ ] In heath checkups screen, dont show cards for measurements done at home
