### ISSUE TITLE
Interface translation to English

### ISSUE THREAD

**Issue by anastasia77705** [UNICEFECAR/parent-buddy-mobile#58]
Email and phone should remain as empty fields. English version will not have phone number. The client will send email address later (after test release).

JSON file in English: https://drive.google.com/file/d/1VUhXdT0vMYmmkQl4jRufXaNf3DPMHivy/view?usp=sharing

**Comment by mi5ha** [comment]
appPhone is used on old AboutScreen and in DidntFindTheAnswerSection (used from FAQ screen, search results)
