### ISSUE TITLE
Search should show keyboard immediately

### ISSUE THREAD

**Issue by mi5ha** [UNICEFECAR/parent-buddy-mobile#92]
Search | UX - the keyboard is not prompted after the search function is invoked. |   |   | Jurica | jurica.babic@fer.hr | Samsung S10+ | New feature | We planned like this |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by MilosByteOut** [comment]
closed 97300595212d161a0aa2ee1cdfb69c001da3aa5c
