### ISSUE TITLE
Smaller profile icon

### ISSUE THREAD

**Issue by mi5ha** [UNICEFECAR/parent-buddy-mobile#93]
Home screen/Articles | (note: just an opinion, not a bug :) ) The top right icon is too big ("user icon"), should be consistent with the search icon wrt padding |   |   | Jurica | jurica.babic@fer.hr | Samsung S10+ | New feature | Design was like this |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by MilosByteOut** [comment]
closed https://github.com/byteout/halo-beba/commit/659da5caa765428269ba59f2fc9140059f868f9a
